/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package talleresfitipaldi;

import Logica_Del_Negocio.Mecanico;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Bakero
 */
public class JDialogPantallaInicio extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPantallaInicio
     */
    ArrayList<Mecanico> lista = new ArrayList<Mecanico>(); 
    Mecanico mecanico;
    JFramePrincipal padre;
    
    
    public JDialogPantallaInicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        padre = (JFramePrincipal) parent;
        
        jLabelPanelAcceso.setForeground(Color.WHITE);
        jLabelContraseña.setForeground(Color.WHITE);
        jLabelUsuario.setForeground(Color.WHITE);
        lista = padre.listaMecanicos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonAcceso = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelPanelAcceso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 170, 30));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 170, 30));

        jButtonAcceso.setText("Acceso");
        jButtonAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAccesoMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 150, -1));

        jLabelUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 110, 20));

        jLabelContraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña");
        jLabelContraseña.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 130, 30));

        jLabelPanelAcceso.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelPanelAcceso.setText("Panel de Acceso");
        jPanel1.add(jLabelPanelAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/67233-mecanica.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAccesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAccesoMouseClicked
        // TODO add your handling code here:
        boolean encontrado = false;
        for (Mecanico mecanico1 : lista) {
            if(jTextFieldUsuario.getText().equals(mecanico1.getUsuario()) && jPasswordField1.getText().equals(mecanico1.getContraseña())){
                encontrado = true;
            }
        }
        if(encontrado){
            padre.setVisible(true);
            padre.aplicacionIniciada=true;
            this.dispose();
        }
        else{
            padre.dispose();
        }
    }//GEN-LAST:event_jButtonAccesoMouseClicked

    /**
     * @param args the command line arguments
     */
    
     public Image getIconImage() {
   Image retValue = Toolkit.getDefaultToolkit().
         getImage(ClassLoader.getSystemResource("Imagen/mecanico.png"));
   return retValue;
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelPanelAcceso;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
