/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package talleresfitipaldi;

import Logica_Del_Negocio.ArrayCliente;
import Logica_Del_Negocio.Cliente;
import Logica_Del_Negocio.Coche;
import Logica_Del_Negocio.Mecanico;
import conexionBD.ConexionBBDD;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author Bakero
 */ 
public class JFramePrincipal extends javax.swing.JFrame {

    /** Creates new form JFramePrincipal */
     JDialogClientes jdialogclientes;
     JDialogVehiculos jDialogVehiculos;
     JDialogReparaciones jdialogReparaciones;
     
     ArrayList<Mecanico> listaMecanicos = new ArrayList<>();
     ArrayList<Cliente> lista;
     ArrayList<Coche> listaCoche;
     ArrayList<String> listaPiezas;
     boolean aplicacionIniciada = false;
     
    ConexionBBDD conexion;
     
    public ArrayList<Cliente> ArrayPapa = new ArrayCliente().getLista();
    public JFramePrincipal() {
        initComponents();
         conexion = new ConexionBBDD("192.168.101.140", "3306", "TallerFiti", "root", "root");
        
         ImageIcon fot = new ImageIcon("src/Imagen/mecanicadia.jpg");
         Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
         jLabel1.setIcon(icono);
         this.repaint();
        
        Mecanico mecanico2 = new Mecanico ("Juan","juan");
        Mecanico mecanico3 = new Mecanico ("Pepe","pepe");
        Mecanico mecanico4 = new Mecanico("Admin","Bakero");
        
        listaMecanicos.add(mecanico2);
        listaMecanicos.add(mecanico3);
        listaMecanicos.add(mecanico4);
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Imagen/mecanico.png"));
        
        this.setTitle("Talleres Fitipaldi");
        lista = new ArrayList();
        listaCoche = new ArrayList();
        listaPiezas = new ArrayList<>();
        
        Cliente c = new Cliente("Pepito", "Palotes", "18053624G", "654985655", "Opel", "Vivaro", "7965kij","Juan");
        Cliente c1 = new Cliente("Pablo", "Pellote", "18049865H", "654552655", "Renaul", "Primastar", "2640fyr","Pepe");
        Cliente c2 = new Cliente("Julieta", "Labordeta", "18046857P", "654562435", "Fiat", "Panda", "2568res","Juan");
        lista.add(c);
        lista.add(c1);
        lista.add(c2);
        
        for (Cliente cl : lista) {
            try{ 
             PreparedStatement consulta  = conexion.getConnection().prepareStatement("SELECT matricula FROM Presupuesto WHERE matricula LIKE ?");
             consulta.setString(1, cl.getMatricula());
             consulta.executeQuery();
             ResultSet rs = consulta.getResultSet();
             rs.next();
             if (!rs.getString(1).equalsIgnoreCase(cl.getMatricula()) ){
                conexion.aniadirBD(cl.getNombre(), cl.getApellidos(), Integer.parseInt(cl.getTelefono()), cl.getDni(), cl.getMarca(), cl.getModelo(), cl.getMatricula());
             }
            } catch (Exception e){
                e.printStackTrace();
            }
            
        }
        
        
        //RELLENAMOS LISTA PARA COMBOBOX ALMACEN
        
        String [] piezas = {"Retrovisor","Luna","turbo","rueda","filtro","Tubo de escape","Limpiaparabrisas","Intermitentes","Frenos","Parachoques"};
        for (String pieza : piezas) {
            listaPiezas.add(pieza);
        }
        
        
        for (Cliente cliente : lista) {
            Coche coche = new Coche(cliente.getMarca(),cliente.getModelo(),cliente.getMatricula(),cliente.getMecanico());
            listaCoche.add(coche);
        }
         if(!aplicacionIniciada){
            this.dispose();
            JDialogPantallaInicio jDialogPantallaInicio = new JDialogPantallaInicio(this, true);
            jDialogPantallaInicio.setVisible(true);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNocturno = new javax.swing.JButton();
        jButtonClientes = new javax.swing.JButton();
        jButtonReparaciones = new javax.swing.JButton();
        jButtonVehiculos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNocturno.setText("Nocturno");
        jButtonNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNocturnoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNocturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 130, 50));

        jButtonClientes.setText("Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 50));

        jButtonReparaciones.setText("Reparaciones");
        jButtonReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReparacionesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReparaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 130, 50));

        jButtonVehiculos.setText("Vehiculos");
        jButtonVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiculosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/mecanicadia.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 620, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        // BOTON CLIENTE
        
        jdialogclientes = new JDialogClientes(this, true);
        jdialogclientes.show();
       
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiculosActionPerformed
        // BOTON VEHICULO
        jDialogVehiculos = new JDialogVehiculos(this, true);
        jDialogVehiculos.show();
        
        
    }//GEN-LAST:event_jButtonVehiculosActionPerformed

    private void jButtonReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReparacionesActionPerformed
        // BOTON REPARACIONES
        jdialogReparaciones = new JDialogReparaciones(this, true);
        jdialogReparaciones.show();
    }//GEN-LAST:event_jButtonReparacionesActionPerformed

    private void jButtonNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNocturnoActionPerformed
        // BOTON NOCTURNO
        if(jButtonNocturno.getText().equals("Nocturno")){
           
            
            ImageIcon fot = new ImageIcon("src/Imagen/mecanicanoche.jpg");
            Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
            jLabel1.setIcon(icono);
            this.repaint();
            
            jButtonNocturno.setText("Diurno");
            jButtonNocturno.setBackground(Color.BLACK);
            jButtonNocturno.setForeground(Color.WHITE);
            
              jButtonClientes.setBackground(Color.BLACK);
            jButtonClientes.setForeground(Color.WHITE);
            
              jButtonReparaciones.setBackground(Color.BLACK);
            jButtonReparaciones.setForeground(Color.WHITE);
            
              jButtonVehiculos.setBackground(Color.BLACK);
            jButtonVehiculos.setForeground(Color.WHITE);
        }
        else  {
           
             
            ImageIcon fot = new ImageIcon("src/Imagen/mecanicadia.jpg");
            Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
            jLabel1.setIcon(icono);
            this.repaint();
             
            jButtonNocturno.setText("Nocturno");
             jButtonNocturno.setBackground(Color.WHITE);
            jButtonNocturno.setForeground(Color.BLACK);
            
              jButtonClientes.setBackground(Color.WHITE);
            jButtonClientes.setForeground(Color.BLACK);
            
              jButtonReparaciones.setBackground(Color.WHITE);
            jButtonReparaciones.setForeground(Color.BLACK);
            
              jButtonVehiculos.setBackground(Color.WHITE);
            jButtonVehiculos.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jButtonNocturnoActionPerformed
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                    new JFramePrincipal();
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonNocturno;
    private javax.swing.JButton jButtonReparaciones;
    private javax.swing.JButton jButtonVehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
